### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by tabishqidwai98** [digipodium/dputils#6]
Documents need to be updated. Please update it ASAP

The libraries are updated, Please Updated the Documents related to it

# Screenshot
![Screenshot 2024-05-16 104406](https://github.com/digipodium/dputils/assets/60247314/7870cdb7-9db4-49a1-8823-65ab185917dd)
![Screenshot 2024-05-16 104646](https://github.com/digipodium/dputils/assets/60247314/b39b10f1-af19-4bea-b9ac-d4c781c06895)

**Comment by tabishqidwai98** [comment]
I need to use it can you please update it sir @zaid-kamil @digipodium/admins

**Comment by zaid-kamil** [comment]
Hi @tabishqidwai98 
sorry, I am not given enough time to update the documentation. I will update it some day. You can look at the example in this notebook given.

[https://github.com/zaid-kamil/2024-feb-pydsda-1100-WTFS/blob/main/scraping/scraper.ipynb](https://github.com/zaid-kamil/2024-feb-pydsda-1100-WTFS/blob/main/scraping/scraper.ipynb)

here is a python database and scaper example
[https://github.com/digipodium/2023-NOV-PYDS-1230-MTWF/blob/main/data%20mining/spider.py](https://github.com/digipodium/2023-NOV-PYDS-1230-MTWF/blob/main/data%20mining/spider.py)

#### Here is the outline logic
Give the URL in the Scraper class instance, the create objects of Tag class, finally use the scraper object  and call its method by passing the tag objects.
